emotions:
  - 'happiness'
  - 'neutral'
  - 'sadness'
  - 'fear'
  - 'angry'

poseTestThreshold: 0.05

attitudeLThreshold: 0.45
attitudeRThreshold: 0.55

timeThreshold: 55  # seconds * 10

facialWeight: 2
vocalWeight: 1
